/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface RjsShadowHost {}
}

declare global {


  interface HTMLRjsShadowHostElement extends Components.RjsShadowHost, HTMLStencilElement {}
  var HTMLRjsShadowHostElement: {
    prototype: HTMLRjsShadowHostElement;
    new (): HTMLRjsShadowHostElement;
  };
  interface HTMLElementTagNameMap {
    'rjs-shadow-host': HTMLRjsShadowHostElement;
  }
}

declare namespace LocalJSX {
  interface RjsShadowHost {}

  interface IntrinsicElements {
    'rjs-shadow-host': RjsShadowHost;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'rjs-shadow-host': LocalJSX.RjsShadowHost & JSXBase.HTMLAttributes<HTMLRjsShadowHostElement>;
    }
  }
}


